### ISSUE TITLE
an option for large numbers rounding

### ISSUE THREAD

**Issue by yegor256** [MikhailEpatko/hoc-badge-action#15]
Would be great to have an option to round large numbers:

```
      - uses: MikhailEpatko/hits-of-code-badge@main
        with:
          output_dir: gh-pages
          filename: hoc-badge.svg
          smallest: K    # could be M or G, the default is "1"
```

If this `smallest` option is missing or set to "1", the value is printed as is. Otherwise, rounded to thousands, millions, or billions
